# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd70c49678264b17d082bea882ef9a51bf851518959964861e429730fc58431e545257f86fae700b98c841624630de5c393587850c62e848f6f83f667be44569

test:
  secret_key_base: 76c479104f9c2bf01d9b50f73cd9ef371eeaa613f5426cd989bf57ce524f90c00c7d4e5b289ca264e474f94b39239196411d6a19b28a0fb492a32c756c3fcd06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
